### ISSUE TITLE
ChangePlan

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-plus#51]
This is a meta issue about changes to the linter. Any new feature would be added here as a checkbox and will be implemented as a PR. An accepted PR would be shown a ticked checkbox. The collaborators can edit this message and add more items after discussion.

- [x] Provide a base class in service (suggested by @joefitzgerald and @park9140)
- [x] Add support for linter priority (suggested by @joefitzgerald)
- [x] Make codebase shine bright (to get accepted upstream)
  - [x] Rewrite views as html5 elements
  - [x] add unit tests
  - [x] reduce extraneous npm package usage 
  - [x] adhere to [single responsibility principle](http://en.wikipedia.org/wiki/Single_responsibility_principle)
  - [x] Remove redundant lodash dependency
  - [x] Make the codebase easier to understand for non-internals people
